name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -o ngrok.zip

    - name: Extract ngrok
      run: unzip ngrok.zip

    - name: Auth with ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop (RDP)
      run: |
        sudo apt update
        sudo apt install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        sudo ufw allow 3389/tcp

    - name: Set Password for "ubuntu" User
      run: echo "ubuntu:P@ssw0rd!" | sudo chpasswd

    - name: Create ngrok Tunnel
      run: ./ngrok tcp 3389
